/*
CS309 - Database Systems
Assignment 2
Clay Buxton
*/

/* [26] */
SELECT COUNT(*) FROM INVOICE;

/* [27] */
SELECT COUNT(*) FROM CUSTOMER WHERE CUS_BALANCE > 500;

/* [28] */
SELECT INVOICE.CUS_CODE, INVOICE.INV_NUMBER, INV_DATE, PRODUCT.P_DESCRIPT,LINE_UNITS,LINE_PRICE
FROM CUSTOMER,INVOICE,LINE,PRODUCT
WHERE CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
/* These set the keys to the same thing */
AND INVOICE.INV_NUMBER = LINE.INV_NUMBER
AND PRODUCT.P_CODE = LINE.P_CODE
ORDER BY INVOICE.CUS_CODE, INVOICE.INV_NUMBER, INVOICE.INV_DATE, PRODUCT.P_DESCRIPT,LINE.LINE_UNITS,
	 LINE.LINE_PRICE
;

/* [29] */
SELECT INVOICE.CUS_CODE, INVOICE.INV_NUMBER, INV_DATE, PRODUCT.P_DESCRIPT,
	LINE_UNITS AS "Units Bought",
	LINE_PRICE AS "Unit Price",
	ROUND(LINE_UNITS * LINE_PRICE,2) AS "Subtotal"

FROM CUSTOMER,INVOICE,LINE,PRODUCT

WHERE CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
/* These set the keys to the same thing */
AND INVOICE.INV_NUMBER = LINE.INV_NUMBER
AND PRODUCT.P_CODE = LINE.P_CODE
ORDER BY INVOICE.CUS_CODE, INVOICE.INV_NUMBER, INVOICE.INV_DATE, PRODUCT.P_DESCRIPT,LINE.LINE_UNITS,
	LINE.LINE_PRICE
;


/* [30] */
SELECT INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE,
	/* This sums the elements from those rows, then rounds it */
	Round(Sum(LINE.LINE_UNITS * LINE.LINE_PRICE),2) AS "Total Purchases"

FROM CUSTOMER, INVOICE, LINE

WHERE CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
AND INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE
ORDER BY INVOICE.CUS_CODE
;

/* [31] */
SELECT INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE,
        /* This sums the elements from those rows, then rounds it */
        Round(Sum(LINE.LINE_UNITS * LINE.LINE_PRICE),2) AS "Total Purchases",
	Count(LINE.LINE_NUMBER) AS "Number of Purchases"

FROM CUSTOMER, INVOICE, LINE

WHERE CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
AND INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE
ORDER BY INVOICE.CUS_CODE
;


/* [32] */

SELECT INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE,
        /* This sums the elements from those rows, then rounds it */
        Round(Sum(LINE.LINE_UNITS * LINE.LINE_PRICE),2) AS "Total Purchases",
        Count(LINE.LINE_NUMBER) AS "Number of Purchases",
	Round((Sum(LINE.LINE_UNITS * LINE.LINE_PRICE) / Count(LINE.LINE_NUMBER)),2) AS "Average Purchase Amount"

FROM CUSTOMER, INVOICE, LINE

WHERE CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
AND INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY INVOICE.CUS_CODE, CUSTOMER.CUS_BALANCE
ORDER BY INVOICE.CUS_CODE
;

/* [33] */












/* 43 */
