/* Quiz */

/* [1] */
ALTER TABLE emp_1
ADD PRIMARY KEY (EMP_NUM);

/* [2] */
ALTER TABLE emp_1
ADD FOREIGN KEY (JOB_CODE) REFERENCES job(JOB_CODE);

/* [3] */
ALTER TABLE emp_1
MODIFY EMP_LNAME varchar(15) NOT NULL;

/* [4] */
ALTER TABLE emp_1
MODIFY EMP_FNAME varchar(15) NOT NULL;

/* [5] */
SELECT * FROM job
WHERE JOB_CODE = 501 OR JOB_CODE = 509;

/* [6] */
SELECT JOB_DESCRIPTION FROM job
WHERE JOB_CHG_HOUR > 50 AND JOB_LAST_UPDATE > "2015-12-01";

/* [7] */
SELECT PROJ_NAME,PROJ_BALANCE FROM PROJECT
WHERE PROJ_BALANCE < 1000000;

/* [8] */
SELECT * FROM EMPLOYEE
WHERE EMP_LNAME LIKE "Smith%";

/* [9] */
SELECT ASSIGN_NUM, ASSIGN_DATE FROM ASSIGNMENT
WHERE EMP_NUM = 117 AND ASSIGN_CHARGE < 100;

/* [10] */
SELECT * FROM JOB
WHERE JOB_CHG_HOUR > 50 AND JOB_CHG_HOUR < 100;

/* [11] */
SELECT EMP_NUM, EMP_FNAME, EMP_LNAME FROM EMPLOYEE
WHERE EMP_INITIAL IS NULL

/* [12] */
SELECT * FROM EMPLOYEE
ORDER BY EMP_YEARS DESC

/* [13] */
SELECT DISTINCT EMP_NUM FROM ASSIGNMENT;

/* [14] */
SELECT * FROM JOB, EMPLOYEE
WHERE EMPLOYEE.JOB_CODE = JOB.JOB_CODE
AND EMP_YEARS > 10;

/* [15] */
SELECT * FROM ASSIGNMENT,EMPLOYEE
WHERE ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM
AND EMPLOYEE.EMP_NUM IN (SELECT EMP_NUM FROM PROJECT);
